# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    az deployment group create --resource-group DevOps --template-file quickstarts/microsoft.documentdb/cosmosdb-create-account/main.bicep --parameter-file quickstarts/microsoft.documentdb/cosmosdb-create-account/azuredeploy.parameters.json
    echo Completed Deployment throug DevOps.
  displayName: 'Run a multi-line script'
